### ISSUE TITLE
Make JSON output human readable again.

### ISSUE THREAD

**Issue by jankeromnes** [espadrine/sc#53]
It costs virtually nothing, and has the immense benefit of making the server a lot more transparent and hackable by default.

You removed the human-readable format in a791dc5e1f223d6698d53e3159797e433b9d9ab9. I disagree. There is no value in saving the few whitespace characters, which get compressed anyway (we don't minify HTML or CSS either before compression, that'd be equally silly). It is considered a [best practice](http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api) to make JSON output human readable by default.

Please revert a791dc5e1f223d6698d53e3159797e433b9d9ab9.

**Comment by espadrine** [comment]
I thought about it prior to making this commit. The idea behind the original code that prettified output was focused on compression not being a factor. But there are other factors, such as space complexity of the algorithm.

More importantly, fundamentally, it is much more logical to put the cost of prettifying it where the need arises, not where it has no relevance. It is trivial to pipe to `jq`, as suggested in the commit, and every devtools has a prettify button.

Finally, `camp` users can trivially choose to prettify their API outputs.

**Comment by jankeromnes** [comment]
I don't think that prettifying the default JSON output costs anything, and any small cost (e.g. somewhat increased space complexity for something that's nearly instant) is significantly outweighed by the added human-readability and direct transparency.

There are no devtools or `jq` when you open an API URL in a browser to watch its results directly, and I'm not sure how well `jq` handles verbose output from `curl -v`, as examples where non-human-readable JSON makes API development a hassle. In general, and as mentioned in the issue description, it is considered a valuable [best practice](http://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api) to make JSON output human readable by default in APIs. Please reconsider.

**Comment by espadrine** [comment]
> I'm not sure how well jq handles verbose output from curl -v

Outstandingly! Curl uses stderr right. Try it: `curl -v https://api.github.com/ | jq .`.

> There are no devtools or jq when you open an API URL in a browser

Nor are there tools to filter the output when it is too large, which jq supports!

But more importantly, it becomes a choice of the library user. You can output human-readable JSON by feeding it human-readable JSON instead.

Obviously, we can't please everyone. Some will hate the use of spaces instead of tabs, some will hate the number of spaces… To be honest, I don't really understand the intensity of those feelings, but I guess if it makes you happier, [let Grace Hopper roll in her grave](https://www.youtube.com/watch?v=JEpsKnWZrJ8) and submit a PR.

**Comment by jankeromnes** [comment]
I yield. Well played sir!
